name: PipelineFlask

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ssrv-ct4u1r2lqhvc73a5jd90
        api-key: ${{ secrets.RENDER_API_KEY }}

    - name: Deploy to EC2 - AWS
      run: |
        echo "Connecting to EC2"
        echo "${{ secrets.DEVOPS_REC }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-52-204-40-120.compute-1.amazonaws.com <<EOF
          cd devops_rec/
          git pull
          ./executar.sh
        EOF
